spring.application.name=QLTT
# data
spring.datasource.url=jdbc:postgresql://localhost:5432/qltt
spring.datasource.username=postgres
spring.datasource.password=123456
# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
# jwt
jwt_secret_key=haydekeynaythatladaicanduocbaomattothon
jwt_expired=86400000